### ISSUE TITLE
python: unable to build standard modules

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#14]
```
OSError: invalid Python installation: unable to open .../src/build-i686/PC/pyconfig.h (No such file or directory)
generate-posix-vars failed
```

pyconfig.h is in build-i686.  If I copy it into PC and run make again, it then says 
```
 CC='i686-w64-mingw32-gcc' LDSHARED='i686-w64-mingw32-gcc -shared -Wl,--enable-a
uto-image-base -pipe -Wl,--dynamicbase,--no-seh -s    ' OPT='-DNDEBUG '        _
TCLTK_INCLUDES='' _TCLTK_LIBS=''        ./python.exe -E ../Python-3.8.7/setup.py
  build
Traceback (most recent call last):
  File "../Python-3.8.7/setup.py", line 2529, in <module>
    main()
  File "../Python-3.8.7/setup.py", line 2487, in main
    set_compiler_flags('CFLAGS', 'PY_CFLAGS_NODIST')
  File "../Python-3.8.7/setup.py", line 96, in set_compiler_flags
    sysconfig.get_config_vars()[compiler_flags] = flags + ' ' + py_flags_nodist
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
make: *** [Makefile:641: sharedmods] Error 1
```

_Originally posted by @jeremyd2019 in https://github.com/msys2/CLANG-packages/issues/11#issuecomment-757422667_

**Comment by jeremyd2019** [comment]
> afair, the build writes some things into `_sysconfigdata__win32_.py` which is then re-used during module builds. So likely some things are missing in that file.

I saw that file and it looked pretty full...  However, given the issue with pyconfig.h, I guess that it may just be in the wrong location for some reason 😕   It is in ...src/build-i686/build/lib.win32-3.8/

[_sysconfigdata__win32_.py.txt](https://github.com/msys2/CLANG-packages/files/5793273/_sysconfigdata__win32_.py.txt)

_Originally posted by @jeremyd2019 in https://github.com/msys2/CLANG-packages/issues/11#issuecomment-757536360_

**Comment by jeremyd2019** [comment]
This also occurs on aarch64.

I had a thought on what may be causing this.  There are several places where MINGW-packages patches to python check if the string "GCC" is in sys.version, to switch between 'normal' windows python behavior and the 'posix build'.  In this case, the sys.version string says "Clang" instead of GCC.

**Comment by jeremyd2019** [comment]
tweaking python to say GCC instead of Clang gets a little further, now it's failing to parse `ld -v`.

**Comment by jeremyd2019** [comment]
Python built on aarch64 with the following patches (as well as disabling LTO, for which clang didn't recognize the compiler options, and PGO, which seemed like just asking for trouble, but will try it next).

* disguise Clang as GCC, as several checks detect the string GCC in `sys.version`
 ```diff
--- Python-3.8.7/Python/getcompiler.c.orig      2021-01-21 00:00:29.237009400 -0800
+++ Python-3.8.7/Python/getcompiler.c   2021-01-21 00:08:07.812256200 -0800
@@ -7,7 +7,7 @@

 // Note the __clang__ conditional has to come before the __GNUC__ one because
 // clang pretends to be GCC.
-#if defined(__clang__)
+#if defined(__clang__) && !defined(_WIN32)
 #define COMPILER "\n[Clang " __clang_version__ "]"
 #elif defined(__GNUC__)
 /* To not break compatibility with things that determine
@@ -18,6 +18,8 @@
 #define COMP_SEP " "
 #if defined(__x86_64__)
 #define ARCH_SUFFIX " 64 bit (AMD64)"
+#elif defined(__aarch64__)
+#define ARCH_SUFFIX " 64 bit (ARM64)"
 #else
 #define ARCH_SUFFIX " 32 bit"
 #endif
```
* Remove anchor from regex that extracts version number from -v/--version output.  The original was confused by a git commit hash in LLD's `ld -v` output.  This doesn't seem entirely safe, but does the trick in this case.
 ```diff
--- Python-3.8.7/Lib/distutils/cygwinccompiler.py~      2021-01-21 00:32:02.844891200 -0800
+++ Python-3.8.7/Lib/distutils/cygwinccompiler.py       2021-01-21 10:58:17.540398500 -0800
@@ -396,7 +396,7 @@
         return (CONFIG_H_UNCERTAIN,
                 "couldn't read '%s': %s" % (fn, exc.strerror))

-RE_VERSION = re.compile(br'[\D\s]*(\d+\.\d+(\.\d+)*)[\D\s]*$')
+RE_VERSION = re.compile(br'[\D\s]*(\d+\.\d+(\.\d+)*)[\D\s]*')

 def _find_exe_version(cmd):
     """Find the version of an executable by running `cmd` in the shell.
```

**Comment by jeremyd2019** [comment]
> Python built on aarch64 with the following patches (as well as disabling LTO, for which clang didn't recognize the compiler options, and PGO, which seemed like just asking for trouble, but will try it next).

It turns out that Python's configure script knows how to do PGO and LTO for both gcc and clang, but keys off of the name in `$CC` to tell which is being used, rather than any smarter compiler detection (like it does a little later in the script).  Adding `export CC=clang` got that working.

**Comment by jeremyd2019** [comment]
Clang's `__VERSION__` (or `__clang_version__`) string is very long, including the git repository url and full commit hash, which was causing python to truncate `sys.version` before the `ARCH_SUFFIX`.  This prevented code from being able to tell ARM64 from AMD64.

I added an ugly hack to create a 'short' version, which allows the whole string to fit.  I don't know if there's anything better pre-defined in Clang - I couldn't find anything.

```diff
--- Python-3.8.7/Python/getcompiler.c.orig      2021-01-21 00:00:29.237009400 -0800
+++ Python-3.8.7/Python/getcompiler.c   2021-01-21 00:08:07.812256200 -0800
@@ -7,7 +7,7 @@

 // Note the __clang__ conditional has to come before the __GNUC__ one because
 // clang pretends to be GCC.
-#if defined(__clang__)
+#if defined(__clang__) && !defined(_WIN32)
 #define COMPILER "\n[Clang " __clang_version__ "]"
 #elif defined(__GNUC__)
 /* To not break compatibility with things that determine
@@ -18,6 +18,8 @@
 #define COMP_SEP " "
 #if defined(__x86_64__)
 #define ARCH_SUFFIX " 64 bit (AMD64)"
+#elif defined(__aarch64__)
+#define ARCH_SUFFIX " 64 bit (ARM64)"
 #else
 #define ARCH_SUFFIX " 32 bit"
 #endif
@@ -25,7 +27,14 @@
 #define COMP_SEP "\n"
 #define ARCH_SUFFIX ""
 #endif
+#if defined(__clang__)
+#define str(x) #x
+#define xstr(x) str(x)
+#define COMPILER COMP_SEP "[GCC Clang " xstr(__clang_major__) "." \
+        xstr(__clang_minor__) "." xstr(__clang_patchlevel__) ARCH_SUFFIX "]"
+#else
 #define COMPILER COMP_SEP "[GCC " __VERSION__ ARCH_SUFFIX "]"
+#endif
 // Generic fallbacks.
 #elif defined(__cplusplus)
 #define COMPILER "[C++]"
```
