### ISSUE TITLE
rust: hardcodes linking libgcc, doesn't build on clang prefix

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#29]
```
lld: error: unable to find library -lgcc_eh
lld: error: unable to find library -lgcc
```

It also seems to hardcode libpthread.a, don't know if that's necessary/desired on a clang/ucrt prefix or if it would be better off using Windows thread API directly.

**Comment by jeremyd2019** [comment]
I'm not seeing anything obvious like a makefile that specify what is being linked.  I did find a source file that seems to specify link options, and lists libraries, but changing that doesn't seem to help.  I hope it isn't something as stupid as being hardcoded in the 'bootstrap' binaries it downloads.

**Comment by jeremyd2019** [comment]
copying libclang_rt.builtins-i386.a to libgcc.a and libunwind.a to libgcc_eh.a allowed it to get further, but still quickly errored out with a message that "the specified procedure could not be found" on proc_macro_error_attr

**Comment by mati865** [comment]
FYI it's defined in https://github.com/rust-lang/rust/blob/dc004d4809f7e5fb5ea73ac630a0b1bdb58eabe4/compiler/rustc_target/src/spec/windows_gnu_base.rs

> copying libclang_rt.builtins-i386.a to libgcc.a and libunwind.a to libgcc_eh.a allowed it to get further, but still quickly errored out with a message that "the specified procedure could not be found" on proc_macro_error_attr

I think it worked for me but it was few releases ago and you will also need to copy `libunwind.dll.a` to `libgcc_s.dll.a`.

**Comment by jeremyd2019** [comment]
Tried again, with the additional library copy `libgcc_s.dll.a`, same result

```
running: T:/mingw-w64-rust/src/i686/build/i686-pc-windows-gnu/stage0/bin/cargo.exe build --manifest-path T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/Cargo.toml
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling winapi-i686-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling syn v1.0.38
   Compiling autocfg v1.0.0
   Compiling version_check v0.9.1
   Compiling memchr v2.3.3
   Compiling serde_derive v1.0.115
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.79
   Compiling log v0.4.11
   Compiling serde v1.0.115
   Compiling regex-syntax v0.6.18
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.59
   Compiling fnv v1.0.7
   Compiling cc v1.0.65
   Compiling itoa v0.4.6
   Compiling unicode-width v0.1.8
   Compiling bootstrap v0.0.0 (T:\mingw-w64-rust\src\rustc-1.49.0-src\src\bootstrap)
   Compiling build_helper v0.1.0 (T:\mingw-w64-rust\src\rustc-1.49.0-src\src\build_helper)
   Compiling thread_local v1.0.1
   Compiling num-traits v0.2.12
   Compiling crossbeam-utils v0.7.2
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling getopts v0.2.21
   Compiling cmake v0.1.44
   Compiling aho-corasick v0.7.13
   Compiling bstr v0.2.13
   Compiling quote v1.0.7
   Compiling num_cpus v1.13.0
   Compiling regex v1.3.9
   Compiling globset v0.4.5
   Compiling winapi-util v0.1.5
   Compiling time v0.1.43
   Compiling filetime v0.2.12
   Compiling opener v0.4.1
   Compiling same-file v1.0.6
error: The specified procedure could not be found. (os error 127)
   --> C:\Users\adminuser\.cargo\registry\src\github.com-1285ae84e5963aae\proc-macro-error-1.0.4\src\lib.rs:284:9
    |
284 | pub use proc_macro_error_attr::proc_macro_error;
    |         ^^^^^^^^^^^^^^^^^^^^^

   Compiling walkdir v2.3.1
error: aborting due to previous error

error: could not compile `proc-macro-error`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "../rustc-1.49.0-src/x.py", line 11, in <module>
    bootstrap.main()
  File "T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/bootstrap.py", line 1074, in main
    bootstrap(help_triggered)
  File "T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/bootstrap.py", line 1047, in bootstrap
    build.build_bootstrap()
  File "T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/bootstrap.py", line 814, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/bootstrap.py", line 145, in run
    raise RuntimeError(err)
RuntimeError: failed to run: T:/mingw-w64-rust/src/i686/build/i686-pc-windows-gnu/stage0/bin/cargo.exe build --manifest-path T:/mingw-w64-rust/src/rustc-1.49.0-src/src/bootstrap/Cargo.toml
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by revelator** [comment]
Seing the same error here, guess we need to ping the rust developer ?.

**Comment by mati865** [comment]
I have made Rust build that doesn't link libgcc but created binaries exit with 127 when using clang subsystem. I'll try with LLVM 12 later.

**Comment by revelator** [comment]
hmm error 127 is'nt that when it cannot find the executable to run ?

**Comment by mati865** [comment]
Proc macros still fail with 127 using LLVM 12.

> hmm error 127 is'nt that when it cannot find the executable to run ?

Yes.

**Comment by revelator** [comment]
looks like a problem running cargo.exe hmm ?!? cant really see whats going on untill i hook up a debugger though.

**Comment by jeremyd2019** [comment]
@mati865 [suggested](https://discord.com/channels/792780131906617355/797787562706075659/842796944308174899) that it may be related to msys2/MINGW-packages#8668

**Comment by mati865** [comment]
Turns out it's something else.
> looks like a problem running cargo.exe hmm ?!? cant really see whats going on untill i hook up a debugger though.

It's the hard part here. What fails here are proc macros and I couldn't find failing binary to run it manually.

**Comment by revelator** [comment]
looks like it was a replacement for the old panic mode, i have a hunch we might need an older version to bootstrap rust for some reason.

**Comment by mati865** [comment]
Looks like static libunwind wrecks havoc in DLL exports:
```
# Last argument: -l:libunwind.dll.a
$ clang "-fno-use-linker-plugin" "-Wl,--nxcompat" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.1pfe0gn2eh7v970e.rcgu.o" "-o" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.dll" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.o1oeznu9ko9dgzy.rcgu.o" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.2ch6uofa9w8rul05.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,--out-implib=D:\\tmp\\export\\target\\debug\\deps\\libexport-fd644ef512a43415.dll.a" "-L" "D:\\tmp\\export\\target\\debug\\deps" "-L" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libproc_macro-fd3382b006356b9a.rlib" "-Wl,--start-group" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-6c3e15b68b7457e1.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-65fd3a937059b64a.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-abaf50bd4f634db5.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-34e548dd170eacb0.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-e01a715bee9dabb1.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-a9c55295aa41fcb2.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-4f42cf642067ea8b.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-ea59bf5f9b8c4ce5.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-291032bfca12fcaa.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-20af5b643e5eb866.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-da770a10915be040.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4b0b9fb18bac02d2.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-f103872556359630.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-1135646032d82c57.rlib" "-Wl,--end-group" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-56170afd0e79cc5d.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o" -l:libunwind.dll.a

$ nm target/debug/deps/libexport-fd644ef512a43415.dll.a | rg make                                                                                                         00000000 T _ZN3std3ffi6os_str5OsStr20make_ascii_lowercase17h657807b7b2306188E
00000000 T __imp__ZN3std3ffi6os_str5OsStr20make_ascii_lowercase17h657807b7b2306188E
00000000 T _ZN3std3ffi6os_str5OsStr20make_ascii_uppercase17ha25d2c9d59057d28E
00000000 T __imp__ZN3std3ffi6os_str5OsStr20make_ascii_uppercase17ha25d2c9d59057d28E

# The same command but the last argument: -l:libunwind.a
$ clang "-fno-use-linker-plugin" "-Wl,--nxcompat" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.1pfe0gn2eh7v970e.rcgu.o" "-o" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.dll" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.o1oeznu9ko9dgzy.rcgu.o" "D:\\tmp\\export\\target\\debug\\deps\\export-fd644ef512a43415.2ch6uofa9w8rul05.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,--out-implib=D:\\tmp\\export\\target\\debug\\deps\\libexport-fd644ef512a43415.dll.a" "-L" "D:\\tmp\\export\\target\\debug\\deps" "-L" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libproc_macro-fd3382b006356b9a.rlib" "-Wl,--start-group" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-6c3e15b68b7457e1.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-65fd3a937059b64a.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-abaf50bd4f634db5.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-34e548dd170eacb0.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-e01a715bee9dabb1.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-a9c55295aa41fcb2.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-4f42cf642067ea8b.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-ea59bf5f9b8c4ce5.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-291032bfca12fcaa.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-20af5b643e5eb866.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-da770a10915be040.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4b0b9fb18bac02d2.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-f103872556359630.rlib" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-1135646032d82c57.rlib" "-Wl,--end-group" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-56170afd0e79cc5d.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "E:\\rustc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o" -l:libunwind.a

$ nm target/debug/deps/libexport-fd644ef512a43415.dll.a | rg make

# nothing shows
```

<details>
<summary>Exports of DLL linked to static libunwind:</summary>

```
$ nm target/debug/deps/libexport-fd644ef512a43415.dll.a

export-fd644ef512a43415.dll:
00000000 i .idata$2
00000000 ? .idata$4
00000000 ? .idata$5
00000000 i .idata$6
00000000 I __IMPORT_DESCRIPTOR_export-fd644ef512a43415
         U __NULL_IMPORT_DESCRIPTOR
         U export-fd644ef512a43415_NULL_THUNK_DATA

export-fd644ef512a43415.dll:
00000000 I __NULL_IMPORT_DESCRIPTOR

export-fd644ef512a43415.dll:
00000000 I export-fd644ef512a43415_NULL_THUNK_DATA

export-fd644ef512a43415.dll:
00000000 T _GCC_specific_handler
00000000 T __imp__GCC_specific_handler

export-fd644ef512a43415.dll:
00000000 T _Unwind_Backtrace
00000000 T __imp__Unwind_Backtrace

export-fd644ef512a43415.dll:
00000000 T _Unwind_DeleteException
00000000 T __imp__Unwind_DeleteException

export-fd644ef512a43415.dll:
00000000 T _Unwind_FindEnclosingFunction
00000000 T __imp__Unwind_FindEnclosingFunction

export-fd644ef512a43415.dll:
00000000 T _Unwind_Find_FDE
00000000 T __imp__Unwind_Find_FDE

export-fd644ef512a43415.dll:
00000000 T _Unwind_ForcedUnwind
00000000 T __imp__Unwind_ForcedUnwind

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetCFA
00000000 T __imp__Unwind_GetCFA

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetDataRelBase
00000000 T __imp__Unwind_GetDataRelBase

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetGR
00000000 T __imp__Unwind_GetGR

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetIP
00000000 T __imp__Unwind_GetIP

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetIPInfo
00000000 T __imp__Unwind_GetIPInfo

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetLanguageSpecificData
00000000 T __imp__Unwind_GetLanguageSpecificData

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetRegionStart
00000000 T __imp__Unwind_GetRegionStart

export-fd644ef512a43415.dll:
00000000 T _Unwind_GetTextRelBase
00000000 T __imp__Unwind_GetTextRelBase

export-fd644ef512a43415.dll:
00000000 T _Unwind_RaiseException
00000000 T __imp__Unwind_RaiseException

export-fd644ef512a43415.dll:
00000000 T _Unwind_Resume
00000000 T __imp__Unwind_Resume

export-fd644ef512a43415.dll:
00000000 T _Unwind_Resume_or_Rethrow
00000000 T __imp__Unwind_Resume_or_Rethrow

export-fd644ef512a43415.dll:
00000000 T _Unwind_SetGR
00000000 T __imp__Unwind_SetGR

export-fd644ef512a43415.dll:
00000000 T _Unwind_SetIP
00000000 T __imp__Unwind_SetIP

export-fd644ef512a43415.dll:
00000000 T __imp_unw_get_fpreg
00000000 T unw_get_fpreg

export-fd644ef512a43415.dll:
00000000 T __imp_unw_get_proc_info
00000000 T unw_get_proc_info

export-fd644ef512a43415.dll:
00000000 T __imp_unw_get_proc_name
00000000 T unw_get_proc_name

export-fd644ef512a43415.dll:
00000000 T __imp_unw_get_reg
00000000 T unw_get_reg

export-fd644ef512a43415.dll:
00000000 T __imp_unw_getcontext
00000000 T unw_getcontext

export-fd644ef512a43415.dll:
00000000 T __imp_unw_init_local
00000000 T unw_init_local

export-fd644ef512a43415.dll:
00000000 T __imp_unw_is_fpreg
00000000 T unw_is_fpreg

export-fd644ef512a43415.dll:
00000000 T __imp_unw_is_signal_frame
00000000 T unw_is_signal_frame

export-fd644ef512a43415.dll:
00000000 D __imp_unw_local_addr_space

export-fd644ef512a43415.dll:
00000000 T __imp_unw_regname
00000000 T unw_regname

export-fd644ef512a43415.dll:
00000000 T __imp_unw_resume
00000000 T unw_resume

export-fd644ef512a43415.dll:
00000000 T __imp_unw_set_fpreg
00000000 T unw_set_fpreg

export-fd644ef512a43415.dll:
00000000 T __imp_unw_set_reg
00000000 T unw_set_reg

export-fd644ef512a43415.dll:
00000000 T __imp_unw_step
00000000 T unw_step

$ llvm-readobj --coff-exports target/debug/deps/export-fd644ef512a43415.dll

File: target/debug/deps/export-fd644ef512a43415.dll
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
Export {
  Ordinal: 0
  Name:
  RVA: 0x0
}
Export {
  Ordinal: 1
  Name: _GCC_specific_handler
  RVA: 0x14460
}
Export {
  Ordinal: 2
  Name: _Unwind_Backtrace
  RVA: 0x3B500
}
Export {
  Ordinal: 3
  Name: _Unwind_DeleteException
  RVA: 0x3B870
}
Export {
  Ordinal: 4
  Name: _Unwind_FindEnclosingFunction
  RVA: 0x3B470
}
Export {
  Ordinal: 5
  Name: _Unwind_Find_FDE
  RVA: 0x3B670
}
Export {
  Ordinal: 6
  Name: _Unwind_ForcedUnwind
  RVA: 0x14EA0
}
Export {
  Ordinal: 7
  Name: _Unwind_GetCFA
  RVA: 0x3B720
}
Export {
  Ordinal: 8
  Name: _Unwind_GetDataRelBase
  RVA: 0x3B390
}
Export {
  Ordinal: 9
  Name: _Unwind_GetGR
  RVA: 0x3B8C0
}
Export {
  Ordinal: 10
  Name: _Unwind_GetIP
  RVA: 0x3B980
}
Export {
  Ordinal: 11
  Name: _Unwind_GetIPInfo
  RVA: 0x3B770
}
Export {
  Ordinal: 12
  Name: _Unwind_GetLanguageSpecificData
  RVA: 0x14F20
}
Export {
  Ordinal: 13
  Name: _Unwind_GetRegionStart
  RVA: 0x14F70
}
Export {
  Ordinal: 14
  Name: _Unwind_GetTextRelBase
  RVA: 0x3B400
}
Export {
  Ordinal: 15
  Name: _Unwind_RaiseException
  RVA: 0x149A0
}
Export {
  Ordinal: 16
  Name: _Unwind_Resume
  RVA: 0x14A10
}
Export {
  Ordinal: 17
  Name: _Unwind_Resume_or_Rethrow
  RVA: 0x3B300
}
Export {
  Ordinal: 18
  Name: _Unwind_SetGR
  RVA: 0x3B920
}
Export {
  Ordinal: 19
  Name: _Unwind_SetIP
  RVA: 0x3B9D0
}
Export {
  Ordinal: 20
  Name: unw_get_fpreg
  RVA: 0x3D130
}
Export {
  Ordinal: 21
  Name: unw_get_proc_info
  RVA: 0x3D2F0
}
Export {
  Ordinal: 22
  Name: unw_get_proc_name
  RVA: 0x3D400
}
Export {
  Ordinal: 23
  Name: unw_get_reg
  RVA: 0x3CFA0
}
Export {
  Ordinal: 24
  Name: unw_getcontext
  RVA: 0x3D6C8
}
Export {
  Ordinal: 25
  Name: unw_init_local
  RVA: 0x3CCB0
}
Export {
  Ordinal: 26
  Name: unw_is_fpreg
  RVA: 0x3D4A0
}
Export {
  Ordinal: 27
  Name: unw_is_signal_frame
  RVA: 0x3D5A0
}
Export {
  Ordinal: 28
  Name: unw_local_addr_space
  RVA: 0x10C2B8
}
Export {
  Ordinal: 29
  Name: unw_regname
  RVA: 0x3D520
}
Export {
  Ordinal: 30
  Name: unw_resume
  RVA: 0x3D380
}
Export {
  Ordinal: 31
  Name: unw_set_fpreg
  RVA: 0x3D1D0
}
Export {
  Ordinal: 32
  Name: unw_set_reg
  RVA: 0x3D040
}
Export {
  Ordinal: 33
  Name: unw_step
  RVA: 0x3D280
}
```

</details>

I'll reduce the example and contact Martin.

**Comment by mati865** [comment]
Good news: I fixed it myself, it was caused by CMake options.
Bad news: we need yet another revision for libunwind so effectively all LLVM packages...

**Comment by revelator** [comment]
:( bad luck.

**Comment by mati865** [comment]
Much further with fixed libunwind but still not quite there:
```
  = note: lld-link: error: unexpected .pdata size: 1620128 is not a multiple of 12
```

**Comment by jeremyd2019** [comment]
> Much further with fixed libunwind but still not quite there:
> 
> ```
>   = note: lld-link: error: unexpected .pdata size: 1620128 is not a multiple of 12
> ```

For some reason this gave me a déjà vu of a commit-message style explanation that some compilers/toolchains pad sections for alignment, so probably multiples of 16.

**Comment by jeremyd2019** [comment]
https://sourceware.org/pipermail/binutils/2010-September/068674.html is the best I could find:

> > I wonder if some sort of error/warning should be generated
> > for section size incorrect.  When is rawsize != size here?
> 
> Well, as padding of pdata is allowed by zero values, we shouldn't warn
> here IMHO.

**Comment by mati865** [comment]
AFAIK rustc asks LLVM to create landing pads.
I'll try to bisect Rust because IIRC it could be built with LLD some time ago. If it doesn't work then maybe something in LLVM/LLD has changed.

**Comment by jeremyd2019** [comment]
OK, I do think it shouldn't error out if the .pdata section is zero-padded to a non-multiple of 12 though.

**Comment by jeremyd2019** [comment]
From @mati865 @ https://discord.com/channels/792780131906617355/814785640667152404/860909628467576842
> Sweet:
> ```
> Build completed successfully in 0:15:01
> ==> Starting package_mingw-w64-clang-x86_64-rust()...
> ```
